name: LLM Lab Mistral 7B Standalone Model Deployment
description: "TBD"
author: "Cloudera"
date: "2023-11-26"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
  PINECONE_API_KEY:
    default: ""
    description: "Required for Pinecone Vector DB: Enter your API Key for Pinecone here. (Shown in API Keys page)"
  PINECONE_ENVIRONMENT:
    default: "gcp-starter"
    description: "Required for Pinecone Vector DB: Enter your Pinecone environment here. (Shown in API Keys page)"
  PINECONE_INDEX:
    default: "cml-default"
    description: "Required for Pinecone Vector DB: The default index is 'cml-default' and can be changed to identify variations for organizations with multiple indexes."

runtimes: 
  - editor: Workbench
    kernel: Python 3.9
    edition: Nvidia GPU
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_install_prerequisites/download_reqs_set_vars.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4